version: "3"

services:
    elasticsearch:
        restart: always
        image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
        environment:
            - "discovery.type=single-node"
        ports:
            - 9200:9200
            - 9300:9300

    kibana:
        restart: always
        depends_on:
            - elasticsearch
        image: docker.elastic.co/kibana/kibana:7.7.0
        ports:
            - 5601:5601

    server:
        image: node:10-alpine
        ports:
            - '8080:3000'
        command: 'npm run start'
